import type { CropName } from "./types";

export interface CropCatalogItem {
  id: string;
  name: CropName;
  category: "Vegetables" | "Pulses & Oilseeds" | "Cereals" | "Commercial Crops";
  marathiName: string;
  hindiName: string;
  icon: string;
  unit: string;
  typicalMarketUnit: string;
  districts: string[];
  exampleMarkets: string[];
  referencePriceMin: number;
  referencePriceModal: number;
  referencePriceMax: number;
  typicalArrivalQty: number;
  buyerDemandLevel: "HIGH" | "MEDIUM" | "LOW";
  storageSuitabilityDays: number;
  image: string;
}

export const MAHARASHTRA_CROP_CATALOG: CropCatalogItem[] = [
  // VEGETABLES
  {
    id: "crop-onion",
    name: "Onion",
    category: "Vegetables",
    marathiName: "कांदा",
    hindiName: "प्याज़",
    icon: "🧅",
    unit: "kg",
    typicalMarketUnit: "Quintal",
    districts: ["Nashik", "Ahilyanagar", "Solapur", "Pune"],
    exampleMarkets: ["Lasalgaon APMC", "Nashik APMC", "Rahuri APMC", "Solapur APMC"],
    referencePriceMin: 22.0,
    referencePriceModal: 25.5,
    referencePriceMax: 28.5,
    typicalArrivalQty: 12500,
    buyerDemandLevel: "HIGH",
    storageSuitabilityDays: 60,
    image: "https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "crop-tomato",
    name: "Tomato",
    category: "Vegetables",
    marathiName: "टोमॅटो",
    hindiName: "टमाटर",
    icon: "🍅",
    unit: "kg",
    typicalMarketUnit: "Quintal",
    districts: ["Nashik", "Pune", "Solapur", "Nagpur", "Chhatrapati Sambhajinagar"],
    exampleMarkets: ["Nashik APMC (Panchavati)", "Pune APMC (Gultekdi)", "Kalamna APMC (Nagpur)"],
    referencePriceMin: 28.5,
    referencePriceModal: 31.5,
    referencePriceMax: 35.0,
    typicalArrivalQty: 4200,
    buyerDemandLevel: "HIGH",
    storageSuitabilityDays: 5,
    image: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "crop-potato",
    name: "Potato",
    category: "Vegetables",
    marathiName: "बटाटा",
    hindiName: "आलू",
    icon: "🥔",
    unit: "kg",
    typicalMarketUnit: "Quintal",
    districts: ["Pune", "Ahilyanagar", "Satara"],
    exampleMarkets: ["Manchar APMC", "Pune APMC", "Ahilyanagar APMC"],
    referencePriceMin: 18.0,
    referencePriceModal: 21.0,
    referencePriceMax: 24.0,
    typicalArrivalQty: 6400,
    buyerDemandLevel: "HIGH",
    storageSuitabilityDays: 45,
    image: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "crop-brinjal",
    name: "Brinjal",
    category: "Vegetables",
    marathiName: "वांगी",
    hindiName: "बैंगन",
    icon: "🍆",
    unit: "kg",
    typicalMarketUnit: "Quintal",
    districts: ["Jalgaon", "Sangli", "Kolhapur"],
    exampleMarkets: ["Jalgaon APMC", "Sangli APMC", "Kolhapur APMC"],
    referencePriceMin: 19.0,
    referencePriceModal: 22.5,
    referencePriceMax: 26.0,
    typicalArrivalQty: 2800,
    buyerDemandLevel: "HIGH",
    storageSuitabilityDays: 4,
    image: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "crop-bhendi",
    name: "Bhendi (Okra)",
    category: "Vegetables",
    marathiName: "भेंडी",
    hindiName: "भिंडी",
    icon: "🌿",
    unit: "kg",
    typicalMarketUnit: "Quintal",
    districts: ["Pune", "Nashik", "Thane"],
    exampleMarkets: ["Pune APMC (Gultekdi)", "Nashik APMC"],
    referencePriceMin: 27.0,
    referencePriceModal: 31.0,
    referencePriceMax: 35.0,
    typicalArrivalQty: 3100,
    buyerDemandLevel: "HIGH",
    storageSuitabilityDays: 3,
    image: "https://images.unsplash.com/photo-1589927986089-35812388d1f4?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "crop-greenchilli",
    name: "Green Chilli",
    category: "Vegetables",
    marathiName: "हिरवी मिरची",
    hindiName: "हरी मिर्च",
    icon: "🌶",
    unit: "kg",
    typicalMarketUnit: "Quintal",
    districts: ["Kolhapur", "Solapur", "Nanded"],
    exampleMarkets: ["Kolhapur APMC", "Solapur APMC", "Nanded APMC"],
    referencePriceMin: 34.0,
    referencePriceModal: 38.5,
    referencePriceMax: 44.0,
    typicalArrivalQty: 2500,
    buyerDemandLevel: "HIGH",
    storageSuitabilityDays: 5,
    image: "https://images.unsplash.com/photo-1588252303782-cb80119abd6d?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "crop-cabbage",
    name: "Cabbage",
    category: "Vegetables",
    marathiName: "कोबी",
    hindiName: "पत्ता गोभी",
    icon: "🥬",
    unit: "kg",
    typicalMarketUnit: "Quintal",
    districts: ["Nashik", "Pune", "Satara"],
    exampleMarkets: ["Nashik APMC", "Pune APMC"],
    referencePriceMin: 12.0,
    referencePriceModal: 15.5,
    referencePriceMax: 18.5,
    typicalArrivalQty: 4800,
    buyerDemandLevel: "MEDIUM",
    storageSuitabilityDays: 10,
    image: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "crop-cauliflower",
    name: "Cauliflower",
    category: "Vegetables",
    marathiName: "फ्लॉवर",
    hindiName: "फूलगोभी",
    icon: "🥦",
    unit: "kg",
    typicalMarketUnit: "Quintal",
    districts: ["Sangli", "Nashik", "Kolhapur"],
    exampleMarkets: ["Sangli APMC", "Nashik APMC"],
    referencePriceMin: 14.0,
    referencePriceModal: 18.0,
    referencePriceMax: 21.0,
    typicalArrivalQty: 3900,
    buyerDemandLevel: "HIGH",
    storageSuitabilityDays: 7,
    image: "https://images.unsplash.com/photo-1568584711075-3d021a7c3ca3?q=80&w=800&auto=format&fit=crop",
  },

  // PULSES & OILSEEDS
  {
    id: "crop-soybean",
    name: "Soybean",
    category: "Pulses & Oilseeds",
    marathiName: "सोयाबीन",
    hindiName: "सोयाबीन",
    icon: "🌱",
    unit: "kg",
    typicalMarketUnit: "Quintal",
    districts: ["Latur", "Nanded", "Akola", "Amravati", "Hingoli"],
    exampleMarkets: ["Latur APMC", "Akola APMC", "Nanded APMC", "Amravati APMC"],
    referencePriceMin: 44.0,
    referencePriceModal: 48.0,
    referencePriceMax: 52.0,
    typicalArrivalQty: 24000,
    buyerDemandLevel: "HIGH",
    storageSuitabilityDays: 180,
    image: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "crop-tur",
    name: "Tur (Pigeon Pea)",
    category: "Pulses & Oilseeds",
    marathiName: "तूर",
    hindiName: "तुअर",
    icon: "🫘",
    unit: "kg",
    typicalMarketUnit: "Quintal",
    districts: ["Nanded", "Latur", "Solapur", "Chhatrapati Sambhajinagar"],
    exampleMarkets: ["Nanded APMC", "Latur APMC", "Solapur APMC"],
    referencePriceMin: 68.0,
    referencePriceModal: 72.0,
    referencePriceMax: 77.0,
    typicalArrivalQty: 12000,
    buyerDemandLevel: "HIGH",
    storageSuitabilityDays: 240,
    image: "https://images.unsplash.com/photo-1515543904379-3d757afe72e3?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "crop-chana",
    name: "Chana (Chickpea)",
    category: "Pulses & Oilseeds",
    marathiName: "हरभरा",
    hindiName: "चना",
    icon: "🟡",
    unit: "kg",
    typicalMarketUnit: "Quintal",
    districts: ["Solapur", "Ahilyanagar", "Dharashiv"],
    exampleMarkets: ["Solapur APMC", "Ahilyanagar APMC"],
    referencePriceMin: 50.0,
    referencePriceModal: 54.0,
    referencePriceMax: 58.0,
    typicalArrivalQty: 8900,
    buyerDemandLevel: "MEDIUM",
    storageSuitabilityDays: 180,
    image: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "crop-groundnut",
    name: "Groundnut",
    category: "Pulses & Oilseeds",
    marathiName: "भुईमूग",
    hindiName: "मूंगफली",
    icon: "🥜",
    unit: "kg",
    typicalMarketUnit: "Quintal",
    districts: ["Amravati", "Dhule", "Kolhapur"],
    exampleMarkets: ["Amravati APMC", "Dhule APMC"],
    referencePriceMin: 54.0,
    referencePriceModal: 58.5,
    referencePriceMax: 63.0,
    typicalArrivalQty: 7500,
    buyerDemandLevel: "HIGH",
    storageSuitabilityDays: 120,
    image: "https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?q=80&w=800&auto=format&fit=crop",
  },

  // CEREALS
  {
    id: "crop-wheat",
    name: "Wheat",
    category: "Cereals",
    marathiName: "गहू",
    hindiName: "गेहूँ",
    icon: "🌾",
    unit: "kg",
    typicalMarketUnit: "Quintal",
    districts: ["Ahilyanagar", "Nashik", "Pune", "Chhatrapati Sambhajinagar"],
    exampleMarkets: ["Ahilyanagar APMC", "Nashik APMC"],
    referencePriceMin: 22.0,
    referencePriceModal: 25.0,
    referencePriceMax: 28.0,
    typicalArrivalQty: 16200,
    buyerDemandLevel: "HIGH",
    storageSuitabilityDays: 360,
    image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "crop-maize",
    name: "Maize",
    category: "Cereals",
    marathiName: "मका",
    hindiName: "मक्का",
    icon: "🌽",
    unit: "kg",
    typicalMarketUnit: "Quintal",
    districts: ["Dhule", "Jalgaon", "Nashik"],
    exampleMarkets: ["Dhule APMC", "Jalgaon APMC"],
    referencePriceMin: 18.5,
    referencePriceModal: 21.5,
    referencePriceMax: 24.5,
    typicalArrivalQty: 21000,
    buyerDemandLevel: "HIGH",
    storageSuitabilityDays: 180,
    image: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "crop-jowar",
    name: "Jowar (Sorghum)",
    category: "Cereals",
    marathiName: "ज्वारी",
    hindiName: "ज्वार",
    icon: "🥣",
    unit: "kg",
    typicalMarketUnit: "Quintal",
    districts: ["Solapur", "Ahilyanagar", "Sangli", "Satara"],
    exampleMarkets: ["Solapur APMC", "Sangli APMC"],
    referencePriceMin: 28.0,
    referencePriceModal: 32.0,
    referencePriceMax: 36.0,
    typicalArrivalQty: 9500,
    buyerDemandLevel: "HIGH",
    storageSuitabilityDays: 240,
    image: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "crop-bajra",
    name: "Bajra (Pearl Millet)",
    category: "Cereals",
    marathiName: "बाजरी",
    hindiName: "बाजरा",
    icon: "🌾",
    unit: "kg",
    typicalMarketUnit: "Quintal",
    districts: ["Ahilyanagar", "Dhule", "Nashik"],
    exampleMarkets: ["Ahilyanagar APMC", "Dhule APMC"],
    referencePriceMin: 21.0,
    referencePriceModal: 24.0,
    referencePriceMax: 27.5,
    typicalArrivalQty: 8200,
    buyerDemandLevel: "MEDIUM",
    storageSuitabilityDays: 180,
    image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?q=80&w=800&auto=format&fit=crop",
  },

  // COMMERCIAL CROPS
  {
    id: "crop-cotton",
    name: "Cotton",
    category: "Commercial Crops",
    marathiName: "कापूस",
    hindiName: "कपास",
    icon: "☁️",
    unit: "kg",
    typicalMarketUnit: "Quintal",
    districts: ["Akola", "Yavatmal", "Amravati", "Jalgaon", "Nanded"],
    exampleMarkets: ["Akola APMC", "Yavatmal APMC", "Jalgaon APMC"],
    referencePriceMin: 58.0,
    referencePriceModal: 62.5,
    referencePriceMax: 67.0,
    typicalArrivalQty: 19500,
    buyerDemandLevel: "HIGH",
    storageSuitabilityDays: 300,
    image: "https://images.unsplash.com/photo-1606041008023-472dfb5e530f?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "crop-sugarcane",
    name: "Sugarcane",
    category: "Commercial Crops",
    marathiName: "ऊस",
    hindiName: "गन्ना",
    icon: "🎋",
    unit: "kg",
    typicalMarketUnit: "Ton",
    districts: ["Kolhapur", "Sangli", "Satara", "Pune"],
    exampleMarkets: ["Kolhapur APMC", "Sangli APMC"],
    referencePriceMin: 2.9,
    referencePriceModal: 3.2,
    referencePriceMax: 3.5,
    typicalArrivalQty: 85000,
    buyerDemandLevel: "HIGH",
    storageSuitabilityDays: 2,
    image: "https://images.unsplash.com/photo-1594282486552-05b4d80fbb9f?q=80&w=800&auto=format&fit=crop",
  },
];

export function getCropCatalogItem(cropName: CropName): CropCatalogItem {
  return (
    MAHARASHTRA_CROP_CATALOG.find(
      (c) => c.name.toLowerCase() === cropName.toLowerCase() || cropName.toLowerCase().includes(c.name.toLowerCase())
    ) || MAHARASHTRA_CROP_CATALOG[0]
  );
}

export function getCropsByCategory(category: CropCatalogItem["category"]): CropCatalogItem[] {
  return MAHARASHTRA_CROP_CATALOG.filter((c) => c.category === category);
}
